name       : python-tzdata
version    : 2023.3
release    : 1
source     :
    - https://files.pythonhosted.org/packages/70/e5/81f99b9fced59624562ab62a33df639a11b26c582be78864b339dafa420d/tzdata-2023.3.tar.gz : 11ef1e08e54acb0d4f95bdb1be05da659673de4acbd21bf9c69e94cc5e907a3a
homepage   : https://github.com/python/tzdata
license    : Apache-2.0
component  : programming.python
summary    : Python package wrapping the IANA time zone database
description: |
    This is a Python package containing zic-compiled binaries for the IANA time zone database. It is intended to be a fallback for systems that do not have system time zone data installed (or don't have it installed in a standard location), as a part of PEP 615
builddeps  :
    - python-build
    - python-installer
    - python-packaging
    - python-wheel
build      : |
    %python3_setup
install    : |
    %python3_install
